# Use an official Node.js runtime as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install --force

# Copy the entire project to the working directory
COPY . .

# Expose the default SvelteKit development port
EXPOSE 5173

# Start the SvelteKit development server with hot-reloading
CMD ["npm", "run", "dev"]
